/* ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : Cpu.c
**     Project     : ProcessorExpert
**     Processor   : MK60DN512VMC10
**     Component   : MK60DN512MC10
**     Version     : Component 01.000, Driver 01.04, CPU db: 3.00.000
**     Datasheet   : K60P144M100SF2V2RM Rev. 2, Jun 2012
**     Compiler    : CodeWarrior ARM C Compiler
**     Date/Time   : 2013-11-11, 14:06, # CodeGen: 107
**     Abstract    :
**
**     Settings    :
**
**     Contents    :
**         No public methods
**
**     Copyright : 1997 - 2012 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/
/*!
** @file Cpu.c
** @version 01.04
** @date 2013-11-11, 14:06, # CodeGen: 107
** @brief
**
*/         
/*!
**  @addtogroup Cpu_module Cpu module documentation
**  @{
*/         

/* MODULE Cpu. */
#include "SPI0_WIFI.h"
#include "PORTA_GPIO.h"
#include "PORTB_GPIO.h"
#include "SPI1_Accel.h"
#include "DISPLAY_SYNC_PWM0.h"
#include "PORTC_GPIO.h"
#include "TU1.h"
#include "I2C1.h"
#include "SPI2_Flash.h"
#include "UART3_WIFI.h"
#include "PORTD_GPIO.h"
#include "PORTE_GPIO.h"
#include "UART0_BT.h"
#include "UART5_DBG.h"
#include "Sleep_Timer_LDD.h"
#include "TU2.h"
#include "ADC0_Vsense.h"
#include "PORTB_GPIO_LDD.h"
#include "PORTC_GPIO_LDD.h"
#include "PORTD_GPIO_LDD.h"
#include "PORTE_GPIO_LDD.h"
#include "USB_CORONA.h"
#include "RNG1.h"
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "Events.h"
#include "Cpu.h"
#include "IO_Map.h"
#include "corona_console.h"

/* Global variables */
volatile uint8_t SR_reg;               /* Current value of the FAULTMASK register */
volatile uint8_t SR_lock = 0x00U;      /* Lock */

/*
** ===================================================================
**     Method      :  Cpu_SetBASEPRI (component MK60DN512MC10)
**
**     Description :
**         This method sets the BASEPRI core register.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void Cpu_SetBASEPRI(register uint32_t Level);

/*
** ===================================================================
**     Method      :  Cpu_INT_NMIInterrupt (component MK60DN512MC10)
**
**     Description :
**         This ISR services the Non Maskable Interrupt interrupt.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_INT_NMIInterrupt)
{
  Cpu_OnNMIINT0();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_Hard_Fault (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_Hard_Fault)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_Mem_Manage_Fault (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_Mem_Manage_Fault)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_Bus_Fault (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_Bus_Fault)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_Usage_Fault (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_Usage_Fault)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_Reserved7 (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_Reserved7)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_Reserved8 (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_Reserved8)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_Reserved9 (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_Reserved9)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_Reserved10 (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_Reserved10)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_SVCall (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_SVCall)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_DebugMonitor (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_DebugMonitor)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_Reserved13 (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_Reserved13)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_PendableSrvReq (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_PendableSrvReq)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_SysTick (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_SysTick)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_DMA0 (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_DMA0)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_DMA1 (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_DMA1)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_DMA2 (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_DMA2)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_DMA3 (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_DMA3)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_DMA4 (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_DMA4)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_DMA5 (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_DMA5)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_DMA6 (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_DMA6)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_DMA7 (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_DMA7)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_DMA8 (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_DMA8)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_DMA9 (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_DMA9)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_DMA10 (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_DMA10)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_DMA11 (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_DMA11)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_DMA12 (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_DMA12)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_DMA13 (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_DMA13)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_DMA14 (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_DMA14)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_DMA15 (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_DMA15)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_DMA_Error (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_DMA_Error)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_MCM (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_MCM)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_FTFL (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_FTFL)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_Read_Collision (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_Read_Collision)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_LVD_LVW (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_LVD_LVW)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_LLW (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_LLW)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_Watchdog (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_Watchdog)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_I2C0 (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_I2C0)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_CAN0_ORed_Message_buffer (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_CAN0_ORed_Message_buffer)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_CAN0_Bus_Off (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_CAN0_Bus_Off)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_CAN0_Error (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_CAN0_Error)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_CAN0_Tx_Warning (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_CAN0_Tx_Warning)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_CAN0_Rx_Warning (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_CAN0_Rx_Warning)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_CAN0_Wake_Up (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_CAN0_Wake_Up)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_I2S0_Tx (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_I2S0_Tx)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_I2S0_Rx (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_I2S0_Rx)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_CAN1_ORed_Message_buffer (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_CAN1_ORed_Message_buffer)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_CAN1_Bus_Off (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_CAN1_Bus_Off)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_CAN1_Error (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_CAN1_Error)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_CAN1_Tx_Warning (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_CAN1_Tx_Warning)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_CAN1_Rx_Warning (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_CAN1_Rx_Warning)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_CAN1_Wake_Up (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_CAN1_Wake_Up)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_Reserved59 (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_Reserved59)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_UART0_LON (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_UART0_LON)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_UART1_RX_TX (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_UART1_RX_TX)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_UART1_ERR (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_UART1_ERR)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_UART2_RX_TX (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_UART2_RX_TX)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_UART2_ERR (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_UART2_ERR)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_UART4_RX_TX (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_UART4_RX_TX)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_UART4_ERR (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_UART4_ERR)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_ADC0 (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_ADC0)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_ADC1 (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_ADC1)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_CMP0 (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_CMP0)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_CMP1 (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_CMP1)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_CMP2 (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_CMP2)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_FTM0 (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_FTM0)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_FTM2 (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_FTM2)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_CMT (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_CMT)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_RTC (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_RTC)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_RTC_Seconds (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_RTC_Seconds)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_PIT0 (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_PIT0)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_PIT1 (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_PIT1)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_PIT2 (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_PIT2)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_PIT3 (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_PIT3)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_PDB0 (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_PDB0)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_USBDCD (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_USBDCD)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_ENET_1588_Timer (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_ENET_1588_Timer)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_ENET_Transmit (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_ENET_Transmit)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_ENET_Receive (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_ENET_Receive)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_ENET_Error (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_ENET_Error)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_Reserved95 (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_Reserved95)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_SDHC (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_SDHC)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_DAC0 (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_DAC0)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_DAC1 (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_DAC1)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_TSI0 (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_TSI0)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_MCG (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_MCG)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_LPTimer (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_LPTimer)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_Reserved102 (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_Reserved102)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_PORTB (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_PORTB)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_PORTC (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_PORTC)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_PORTD (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_PORTD)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_Reserved108 (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_Reserved108)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_Reserved109 (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_Reserved109)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_SWI (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_SWI)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_Reserved111 (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_Reserved111)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_Reserved112 (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_Reserved112)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_Reserved113 (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_Reserved113)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_Reserved114 (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_Reserved114)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_Reserved115 (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_Reserved115)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_Reserved116 (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_Reserved116)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_Reserved117 (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_Reserved117)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_Reserved118 (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_Reserved118)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_Reserved119 (component MK60DN512MC10)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_Reserved119)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  wassert_reboot();
}

/*
 *   Init the BT chip and assure that it comes up properly.
 */

#define     MAX_BT_INIT_RETRIES      (4)
#define     MAX_CTS_LOW_LOOPS   (0xFFFFFF)
#define     MAX_CTS_HIGH_LOOPS  (0xFFFFFF)

static void _init_bt_chip(void)
{
    uint8_t  g_BT_init_passed = 0;
    uint32_t g_num_loops_cts_low;
    uint32_t g_num_loops_cts_high;
    uint32_t g_num_BT_retries = 0;
    
    PORTD_PCR5 = PORT_PCR_MUX(0x01);
    GPIOD_PDDR &= ~0x20;  // BT_CTS is an input.
    
    while( g_num_BT_retries < MAX_BT_INIT_RETRIES )
    {
        g_num_loops_cts_low = 0;
        g_num_loops_cts_high = 0;
        
        /*
         *   Reset the BT Chip, fast clock and slow clock.
         *   
         *   We don't have the timer peripheral up yet, so we are just using
         *   arbitrary busy waits.
         */
        PORTB_GPIO_LDD_SetFieldValue(NULL, BT_PWDN_B, 0);
        PORTE_GPIO_LDD_SetFieldValue(NULL, BT_32KHz_EN, 1);

        PORTD_PCR4 = PORT_PCR_MUX(0x01);
        GPIOD_PDDR |= 0x10; // pin 4 is an output now
        GPIOD_PDOR |= 0x10; // pin 4 is BT_RTS
    #if 0
        PORTD_PCR7 = PORT_PCR_MUX(0x01);
        GPIOD_PDDR |= 0x80; // pin 7 is an output now
        GPIOD_PDOR |= 0x80; // pin 7 is BT_TXD
    #endif
        
        //quick_sleep(1300 * 1000);   // 32KHz takes some time to come up.
        sleep(100);
        
        //PORTE_GPIO_LDD_SetFieldValue(NULL, BT_32KHz_EN, 1);
        //quick_sleep(750 * 1000);   // BT slow clock should be up before BT comes up.
        
        PORTB_GPIO_LDD_SetFieldValue(NULL, BT_PWDN_B, 1);
        
        // Read back BT_CTS:  should be high, then go back low, when its done initializing.

        while( 0 == (GPIOD_PDIR & 0x20) )
        {
            g_num_loops_cts_low++;
            
            if(g_num_loops_cts_low >= MAX_CTS_LOW_LOOPS)
            {
                goto bt_init_retry;
            }
        }
        
        while( GPIOD_PDIR & 0x20 )
        {
            g_num_loops_cts_high++;
            
            if(g_num_loops_cts_high >= MAX_CTS_HIGH_LOOPS)
            {
                goto bt_init_retry;
            }
        }
        
        g_BT_init_passed = 1;
        return;
        
        bt_init_retry:
            g_num_BT_retries++;
    }
}


/*
 *   Because resetting the BT chip is known to cause the 32KHz signal out of the Silego
 *     to wiggle, we want to do all of the resetting BEFORE we switch over to using the
 *     32KHz from the Silego.
 */
void _do_gpio_stuff(void)
{
    /* PORTE_ISFR: ISF=6 */
    PORTE_ISFR = PORT_ISFR_ISF(0x06);  
    
    /* PORTA_DFCR: CS=0 */
    PORTA_DFCR &= (uint32_t)~(uint32_t)(PORT_DFCR_CS_MASK);                                   
    /* PORTA_DFWR: FILT=0 */
    PORTA_DFWR &= (uint32_t)~(uint32_t)(PORT_DFWR_FILT(0x1F));                                   
    /* NVICISER2: SETENA|=0x08800000 */
    NVICISER2 |= NVIC_ISER_SETENA(0x08800000);                                   
    /* PORTB_DFCR: CS=0 */
    PORTB_DFCR &= (uint32_t)~(uint32_t)(PORT_DFCR_CS_MASK);                                   
    /* PORTB_DFWR: FILT=0 */
    PORTB_DFWR &= (uint32_t)~(uint32_t)(PORT_DFWR_FILT(0x1F));                                   
    /* PORTC_DFCR: CS=0 */
    PORTC_DFCR &= (uint32_t)~(uint32_t)(PORT_DFCR_CS_MASK);                                   
    /* PORTC_DFWR: FILT=0 */
    PORTC_DFWR &= (uint32_t)~(uint32_t)(PORT_DFWR_FILT(0x1F));
    /* PORTC_DFCR: CS=0 */
    PORTC_DFCR &= (uint32_t)~(uint32_t)(PORT_DFCR_CS_MASK);                                   
    /* PORTC_DFWR: FILT=0 */
    PORTC_DFWR &= (uint32_t)~(uint32_t)(PORT_DFWR_FILT(0x1F));                                   
    /* PORTC_PCR19: ISF=0,MUX=1 */
    PORTC_PCR19 = (uint32_t)((PORTC_PCR19 & (uint32_t)~(uint32_t)(
                   PORT_PCR_ISF_MASK |
                   PORT_PCR_MUX(0x06)
                  )) | (uint32_t)(
                   PORT_PCR_MUX(0x01)
                  ));
    /* PORTD_PCR0: ISF=0,MUX=1,PE=1,PS=1 */
    PORTD_PCR0 = (uint32_t)((PORTD_PCR0 & (uint32_t)~(uint32_t)(
                  PORT_PCR_ISF_MASK |
                  PORT_PCR_MUX(0x06)
                 )) | (uint32_t)(
                  PORT_PCR_MUX(0x01) |
                  PORT_PCR_PE_MASK |
                  PORT_PCR_PS_MASK
                 ));                                  
    /* PORTD_DFCR: CS=0 */
    PORTD_DFCR &= (uint32_t)~(uint32_t)(PORT_DFCR_CS_MASK);                                   
    /* PORTD_DFWR: FILT=0 */
    PORTD_DFWR &= (uint32_t)~(uint32_t)(PORT_DFWR_FILT(0x1F));                                   
    /* PORTE_PCR1: ISF=0,IRQC=0x0A,MUX=1,PE=1,PS=1 */
    PORTE_PCR1 = (uint32_t)((PORTE_PCR1 & (uint32_t)~(uint32_t)(
                  PORT_PCR_ISF_MASK |
                  PORT_PCR_IRQC(0x05) |
                  PORT_PCR_MUX(0x06)
                 )) | (uint32_t)(
                  PORT_PCR_IRQC(0x0A) |
                  PORT_PCR_MUX(0x01) |
                  PORT_PCR_PE_MASK |
                  PORT_PCR_PS_MASK
                 ));                                  
    /* PORTE_PCR2: ISF=0,IRQC=0x0A,MUX=1,PE=1,PS=1 */
    PORTE_PCR2 = (uint32_t)((PORTE_PCR2 & (uint32_t)~(uint32_t)(
                  PORT_PCR_ISF_MASK |
                  PORT_PCR_IRQC(0x05) |
                  PORT_PCR_MUX(0x06)
                 )) | (uint32_t)(
                  PORT_PCR_IRQC(0x0A) |
                  PORT_PCR_MUX(0x01) |
                  PORT_PCR_PE_MASK |
                  PORT_PCR_PS_MASK
                 ));                                  
    /* PORTE_DFCR: CS=0 */
    PORTE_DFCR &= (uint32_t)~(uint32_t)(PORT_DFCR_CS_MASK);                                   
    /* PORTE_DFWR: FILT=0 */
    PORTE_DFWR &= (uint32_t)~(uint32_t)(PORT_DFWR_FILT(0x1F));                                   
    /* PORTE_PCR5: ISF=0,MUX=1 */
    PORTE_PCR5 = (uint32_t)((PORTE_PCR5 & (uint32_t)~(uint32_t)(
                  PORT_PCR_ISF_MASK |
                  PORT_PCR_MUX(0x06)
                 )) | (uint32_t)(
                  PORT_PCR_MUX(0x01)
                 ));                              
    
    /* ### Init_GPIO "PORTA_GPIO" init code ... */
    PORTA_GPIO_Init();
    /* ### Init_GPIO "PORTB_GPIO" init code ... */
    PORTB_GPIO_Init();
    /* ### Init_GPIO "PORTC_GPIO" init code ... */
    PORTC_GPIO_Init();
    /* ### Init_GPIO "PORTD_GPIO" init code ... */
    PORTD_GPIO_Init();
    /* ### Init_GPIO "PORTE_GPIO" init code ... */
    PORTE_GPIO_Init();
    /* ### GPIO_LDD "PORTB_GPIO_LDD" component auto initialization. Auto initialization feature can be disabled by component property "Auto initialization". */
    (void)PORTB_GPIO_LDD_Init(NULL);
    /* ### GPIO_LDD "PORTC_GPIO_LDD" component auto initialization. Auto initialization feature can be disabled by component property "Auto initialization". */
    (void)PORTC_GPIO_LDD_Init(NULL);
    /* ### GPIO_LDD "PORTD_GPIO_LDD" component auto initialization. Auto initialization feature can be disabled by component property "Auto initialization". */
    (void)PORTD_GPIO_LDD_Init(NULL);
    /* ### GPIO_LDD "PORTE_GPIO_LDD" component auto initialization. Auto initialization feature can be disabled by component property "Auto initialization". */
    (void)PORTE_GPIO_LDD_Init(NULL);

    /*
     *   Reset the BT Chip, fast clock and slow clock.
     *   
     *   We don't have the timer peripheral up yet, so we are just using
     *   arbitrary busy waits.
     */
    _init_bt_chip();
}

/*
 *   32KHz version of PE_low_level_init().
 */
void PE_low_level_init_32KHz(void)
{
  #ifdef PEX_RTOS_INIT
    PEX_RTOS_INIT();                   /* Initialization of the selected RTOS. Macro is defined by the RTOS component. */
  #endif
      /* Initialization of the SIM module */
  /* PORTA_PCR4: ISF=0,MUX=7 */
  PORTA_PCR4 = (uint32_t)((PORTA_PCR4 & (uint32_t)~(uint32_t)(
                PORT_PCR_ISF_MASK
               )) | (uint32_t)(
                PORT_PCR_MUX(0x07)
               ));                                  
        /* Initialization of the RCM module */
  /* RCM_RPFW: RSTFLTSEL=0 */
  RCM_RPFW &= (uint8_t)~(uint8_t)(RCM_RPFW_RSTFLTSEL(0x1F));                                   
  /* RCM_RPFC: RSTFLTSS=0,RSTFLTSRW=0 */
  RCM_RPFC &= (uint8_t)~(uint8_t)(
               RCM_RPFC_RSTFLTSS_MASK |
               RCM_RPFC_RSTFLTSRW(0x03)
              );                                   
  /* SIM_SCGC7: MPU=1 */
  SIM_SCGC7 |= SIM_SCGC7_MPU_MASK;                                   
        /* Initialization of the MPU module */
  /* MPU_CESR: SPERR=0,VLD=0 */
  MPU_CESR &= (uint32_t)~(uint32_t)((MPU_CESR_SPERR(0x1F) | MPU_CESR_VLD_MASK));                                   
      /* Initialization of the PMC module */
  /* PMC_LVDSC1: LVDACK=1,LVDIE=0,LVDRE=1,LVDV=0 */
  PMC_LVDSC1 = (uint8_t)((PMC_LVDSC1 & (uint8_t)~(uint8_t)(
                PMC_LVDSC1_LVDIE_MASK |
                PMC_LVDSC1_LVDV(0x03)
               )) | (uint8_t)(
                PMC_LVDSC1_LVDACK_MASK |
                PMC_LVDSC1_LVDRE_MASK
               ));                                  
  /* PMC_LVDSC2: LVWACK=1,LVWIE=0,LVWV=0 */
  PMC_LVDSC2 = (uint8_t)((PMC_LVDSC2 & (uint8_t)~(uint8_t)(
                PMC_LVDSC2_LVWIE_MASK |
                PMC_LVDSC2_LVWV(0x03)
               )) | (uint8_t)(
                PMC_LVDSC2_LVWACK_MASK
               ));                                  
  /* PMC_REGSC: BGEN=0,ACKISO=0,BGBE=0 */
  PMC_REGSC &= (uint8_t)~(uint8_t)(
                PMC_REGSC_BGEN_MASK |
                PMC_REGSC_ACKISO_MASK |
                PMC_REGSC_BGBE_MASK
               );      
  
  // For good measure, remove the 26MHz MCU clock.
  GPIOC_PDOR &= ~0x80000;
  
#if 0  // This is already done in BOOT2.
  
  /* SMC_PMPROT: ??=0,??=0,AVLP=1,??=0,ALLS=1,??=0,AVLLS=1,??=0 */
  SMC_PMPROT = SMC_PMPROT_AVLP_MASK |
               SMC_PMPROT_ALLS_MASK |
               SMC_PMPROT_AVLLS_MASK;  /* Setup Power mode protection register */
#endif
  
  /* Common initialization of the CPU registers */
                                 
  /* Common initialization of the CPU registers */
  /* NVICIP87: PRI87=0 */
  NVICIP87 = NVIC_IP_PRI87(0x00);                                   
  /* NVICIP88: PRI88=0 */
  NVICIP88 = NVIC_IP_PRI88(0x00);                                   
  /* NVICIP90: PRI90=0 */
  NVICIP90 = NVIC_IP_PRI90(0x00);                                   
  /* NVICIP91: PRI91=0 */
  NVICIP91 = NVIC_IP_PRI91(0x00);                                   
  /* NVICIP73: PRI73=0 */
  NVICIP73 = NVIC_IP_PRI73(0x00);                                   
  /* NVICIP20: PRI20=0 */
  NVICIP20 = NVIC_IP_PRI20(0x00);                                   

  /* ### RNG_LDD "RNG1" init code ... */
  /* Enable interrupts of the given priority level */
  Cpu_SetBASEPRI(0U);
}


/*
 *   32kHz version of __init_hardware().
 */
void __init_hardware(void)
{

  /*** !!! Here you can place your own code before PE initialization using property "User code before PE initialization" on the build options tab. !!! ***/

  /*** ### MK60DN512VMC10 "Cpu" init code ... ***/
  /*** PE initialization code after reset ***/
  SCB_VTOR = (uint32_t)(&__vect_table); /* Set the interrupt vector table position */
  /* SIM_SCGC6: RTC=1 */
  SIM_SCGC6 |= SIM_SCGC6_RTC_MASK;                                   
  if ((RTC_CR & RTC_CR_OSCE_MASK) == 0u) { /* Only if the OSCILLATOR is not already enabled */
    /* RTC_CR: SC2P=0,SC4P=0,SC8P=0,SC16P=0 */
    RTC_CR &= (uint32_t)~(uint32_t)(
               RTC_CR_SC2P_MASK |
               RTC_CR_SC4P_MASK |
               RTC_CR_SC8P_MASK |
               RTC_CR_SC16P_MASK
              );
    /* RTC_CR: OSCE=1 */
    RTC_CR |= RTC_CR_OSCE_MASK;                                   
    /* RTC_CR: CLKO=0 */
    RTC_CR &= (uint32_t)~(uint32_t)(RTC_CR_CLKO_MASK);                                   
  }
  /* Disable the WDOG module */
  /* WDOG_UNLOCK: WDOGUNLOCK=0xC520 */
  WDOG_UNLOCK = WDOG_UNLOCK_WDOGUNLOCK(0xC520); /* Key 1 */
  /* WDOG_UNLOCK: WDOGUNLOCK=0xD928 */
  WDOG_UNLOCK = WDOG_UNLOCK_WDOGUNLOCK(0xD928); /* Key 2 */
  /* WDOG_STCTRLH: ??=0,DISTESTWDOG=0,BYTESEL=0,TESTSEL=0,TESTWDOG=0,??=0,??=1,WAITEN=1,STOPEN=1,DBGEN=0,ALLOWUPDATE=1,WINEN=0,IRQRSTEN=0,CLKSRC=1,WDOGEN=0 */
  WDOG_STCTRLH = WDOG_STCTRLH_BYTESEL(0x00) |
                 WDOG_STCTRLH_WAITEN_MASK |
                 WDOG_STCTRLH_STOPEN_MASK |
                 WDOG_STCTRLH_ALLOWUPDATE_MASK |
                 WDOG_STCTRLH_CLKSRC_MASK |
                 0x0100U;  
  
  /*
   *   Allow some delay in case we're coming up from some stupid state.
   */
  quick_sleep(50 * 1000);
  
  /* System clock initialization */
  /* SIM_SCGC5: PORTE=1,PORTD=1,PORTC=1,PORTB=1,PORTA=1 */
  SIM_SCGC5 |= SIM_SCGC5_PORTE_MASK |
               SIM_SCGC5_PORTD_MASK |
               SIM_SCGC5_PORTC_MASK |
               SIM_SCGC5_PORTB_MASK |
               SIM_SCGC5_PORTA_MASK;   /* Enable clock gate for ports to enable pin routing */
  /* SIM_CLKDIV1: OUTDIV1=0,OUTDIV2=0,OUTDIV3=0,OUTDIV4=1,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0 */
  SIM_CLKDIV1 = SIM_CLKDIV1_OUTDIV1(0x00) |
                SIM_CLKDIV1_OUTDIV2(0x00) |
                SIM_CLKDIV1_OUTDIV3(0x00) |
                SIM_CLKDIV1_OUTDIV4(0x01); /* Update system prescalers */
  
  
  /*
   *    Enable GPIO's here, before we start sourcing from anything on the Silego!
   */
  _do_gpio_stuff();
  
  /* SIM_SOPT2: PLLFLLSEL=0 */
  SIM_SOPT2 &= (uint32_t)~(uint32_t)(SIM_SOPT2_PLLFLLSEL_MASK); /* Select FLL as a clock source for various peripherals */
  /* SIM_SOPT1: OSC32KSEL=0 */
  SIM_SOPT1 &= (uint32_t)~(uint32_t)(SIM_SOPT1_OSC32KSEL(0x03)); /* System oscillator drives 32 kHz clock for various peripherals */
  /* Switch to FEE Mode */
  /* MCG_C2: LOCRE0=0,??=0,RANGE0=0,HGO0=0,EREFS0=0,LP=0,IRCS=0 */
  MCG_C2 = MCG_C2_RANGE0(0x00);                                   
  /* OSC_CR: ERCLKEN=1,??=0,EREFSTEN=0,??=0,SC2P=0,SC4P=0,SC8P=0,SC16P=0 */
  OSC_CR = OSC_CR_ERCLKEN_MASK;                                   
  /* MCG_C7: OSCSEL=1 */
  MCG_C7 |= MCG_C7_OSCSEL_MASK;                                   
  /* MCG_C1: CLKS=0,FRDIV=0,IREFS=0,IRCLKEN=1,IREFSTEN=0 */
  MCG_C1 = (MCG_C1_CLKS(0x00) | MCG_C1_FRDIV(0x00) | MCG_C1_IRCLKEN_MASK);                                   
  /* MCG_C4: DMX32=1,DRST_DRS=1 */
  MCG_C4 = (uint8_t)((MCG_C4 & (uint8_t)~(uint8_t)(
            MCG_C4_DRST_DRS(0x02)
           )) | (uint8_t)(
            MCG_C4_DMX32_MASK |
            MCG_C4_DRST_DRS(0x01)
           ));                                  
  /* MCG_C5: ??=0,PLLCLKEN0=0,PLLSTEN0=0,PRDIV0=0 */
  MCG_C5 = MCG_C5_PRDIV0(0x00);                                   
  /* MCG_C6: LOLIE0=0,PLLS=0,CME0=0,VDIV0=0 */
  MCG_C6 = MCG_C6_VDIV0(0x00);                                   
  while((MCG_S & MCG_S_IREFST_MASK) != 0x00U) { /* Check that the source of the FLL reference clock is the external reference clock. */
  }
  while((MCG_S & 0x0CU) != 0x00U) {    /* Wait until output of the FLL is selected */
  }
  /*** End of PE initialization code after reset ***/

  /*** !!! Here you can place your own code after PE initialization using property "User code after PE initialization" on the build options tab. !!! ***/
  PE_low_level_init_32KHz();
}


/*** !!! Here you can place your own code using property "User data declarations" on the build options tab. !!! ***/

/*lint -esym(765,__init_hardware) Disable MISRA rule (8.10) checking for symbols (__init_hardware). The function is linked to the EWL library */
/*lint -esym(765,Cpu_Interrupt) Disable MISRA rule (8.10) checking for symbols (Cpu_Interrupt). */
void __init_hardware_26MHz(void)
{

  /*** !!! Here you can place your own code before PE initialization using property "User code before PE initialization" on the build options tab. !!! ***/

  /*** ### MK60DN512VMC10 "Cpu" init code ... ***/
  /*** PE initialization code after reset ***/
  SCB_VTOR = (uint32_t)(&__vect_table); /* Set the interrupt vector table position */
  /* SIM_SCGC6: RTC=1 */
  SIM_SCGC6 |= SIM_SCGC6_RTC_MASK;                                   
  if ((RTC_CR & RTC_CR_OSCE_MASK) == 0u) { /* Only if the OSCILLATOR is not already enabled */
    /* RTC_CR: SC2P=0,SC4P=0,SC8P=0,SC16P=0 */
    RTC_CR &= (uint32_t)~(uint32_t)(
               RTC_CR_SC2P_MASK |
               RTC_CR_SC4P_MASK |
               RTC_CR_SC8P_MASK |
               RTC_CR_SC16P_MASK
              );                                   
    /* RTC_CR: OSCE=1 */
    RTC_CR |= RTC_CR_OSCE_MASK;                                   
    /* RTC_CR: CLKO=0 */
    RTC_CR &= (uint32_t)~(uint32_t)(RTC_CR_CLKO_MASK);                                   
  }
  /* Disable the WDOG module */
  /* WDOG_UNLOCK: WDOGUNLOCK=0xC520 */
  WDOG_UNLOCK = WDOG_UNLOCK_WDOGUNLOCK(0xC520); /* Key 1 */
  /* WDOG_UNLOCK: WDOGUNLOCK=0xD928 */
  WDOG_UNLOCK = WDOG_UNLOCK_WDOGUNLOCK(0xD928); /* Key 2 */
  /* WDOG_STCTRLH: ??=0,DISTESTWDOG=0,BYTESEL=0,TESTSEL=0,TESTWDOG=0,??=0,??=1,WAITEN=1,STOPEN=1,DBGEN=0,ALLOWUPDATE=1,WINEN=0,IRQRSTEN=0,CLKSRC=1,WDOGEN=0 */
  WDOG_STCTRLH = WDOG_STCTRLH_BYTESEL(0x00) |
                 WDOG_STCTRLH_WAITEN_MASK |
                 WDOG_STCTRLH_STOPEN_MASK |
                 WDOG_STCTRLH_ALLOWUPDATE_MASK |
                 WDOG_STCTRLH_CLKSRC_MASK |
                 0x0100U;       
  
  /*
   *   Allow some delay in case we're coming up from some stupid state.
   */
  quick_sleep(50 * 1000);
  
  /* System clock initialization */
  /* SIM_SCGC5: PORTE=1,PORTD=1,PORTC=1,PORTB=1,PORTA=1 */
  SIM_SCGC5 |= SIM_SCGC5_PORTE_MASK |
               SIM_SCGC5_PORTD_MASK |
               SIM_SCGC5_PORTC_MASK |
               SIM_SCGC5_PORTB_MASK |
               SIM_SCGC5_PORTA_MASK;   /* Enable clock gate for ports to enable pin routing */
  
  // Turn on the 26MHz MCU clock.
  GPIOC_PDOR |= 0x80000;
  sleep(5);
  
  /* SIM_CLKDIV1: OUTDIV1=1,OUTDIV2=1,OUTDIV3=3,OUTDIV4=3,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0 */
  SIM_CLKDIV1 = SIM_CLKDIV1_OUTDIV1(0x01) |
                SIM_CLKDIV1_OUTDIV2(0x01) |
                SIM_CLKDIV1_OUTDIV3(0x03) |
                SIM_CLKDIV1_OUTDIV4(0x03); /* Update system prescalers */
  
  
  /*
   *    Enable GPIO's here, before we start sourcing from anything on the Silego!
   */
  _do_gpio_stuff();
  
  /* SIM_SOPT2: PLLFLLSEL=1 */
  SIM_SOPT2 |= SIM_SOPT2_PLLFLLSEL_MASK; /* Select PLL as a clock source for various peripherals */
  /* SIM_SOPT1: OSC32KSEL=0 */
  SIM_SOPT1 &= (uint32_t)~(uint32_t)(SIM_SOPT1_OSC32KSEL(0x03)); /* System oscillator drives 32 kHz clock for various peripherals */
  /* PORTA_PCR18: ISF=0,MUX=0 */
  PORTA_PCR18 &= (uint32_t)~(uint32_t)((PORT_PCR_ISF_MASK | PORT_PCR_MUX(0x07)));                                   
  /* Switch to FBE Mode */
  /* MCG_C2: LOCRE0=0,??=0,RANGE0=2,HGO0=0,EREFS0=0,LP=0,IRCS=0 */
  MCG_C2 = MCG_C2_RANGE0(0x02);                                   
  /* OSC_CR: ERCLKEN=1,??=0,EREFSTEN=0,??=0,SC2P=0,SC4P=0,SC8P=0,SC16P=0 */
  OSC_CR = OSC_CR_ERCLKEN_MASK;                                   
  /* MCG_C7: OSCSEL=0 */
  MCG_C7 &= (uint8_t)~(uint8_t)(MCG_C7_OSCSEL_MASK);                                   
  /* MCG_C1: CLKS=2,FRDIV=5,IREFS=0,IRCLKEN=1,IREFSTEN=0 */
  MCG_C1 = (MCG_C1_CLKS(0x02) | MCG_C1_FRDIV(0x05) | MCG_C1_IRCLKEN_MASK);                                   
  /* MCG_C4: DMX32=0,DRST_DRS=0 */
  MCG_C4 &= (uint8_t)~(uint8_t)((MCG_C4_DMX32_MASK | MCG_C4_DRST_DRS(0x03)));                                   
  /* MCG_C5: ??=0,PLLCLKEN0=0,PLLSTEN0=0,PRDIV0=0x0C */
  MCG_C5 = MCG_C5_PRDIV0(0x0C);                                   
  /* MCG_C6: LOLIE0=0,PLLS=0,CME0=0,VDIV0=0 */
  MCG_C6 = MCG_C6_VDIV0(0x00);                                   
  while((MCG_S & MCG_S_IREFST_MASK) != 0x00U) { /* Check that the source of the FLL reference clock is the external reference clock. */
  }
  while((MCG_S & 0x0CU) != 0x08U) {    /* Wait until external reference clock is selected as MCG output */
  }
  /* Switch to PBE Mode */
  /* MCG_C6: LOLIE0=0,PLLS=1,CME0=0,VDIV0=0 */
  MCG_C6 = (MCG_C6_PLLS_MASK | MCG_C6_VDIV0(0x00));                                   
  while((MCG_S & 0x0CU) != 0x08U) {    /* Wait until external reference clock is selected as MCG output */
  }
  while((MCG_S & MCG_S_LOCK0_MASK) == 0x00U) { /* Wait until locked */
  }
  /* Switch to PEE Mode */
  /* MCG_C1: CLKS=0,FRDIV=5,IREFS=0,IRCLKEN=1,IREFSTEN=0 */
  MCG_C1 = (MCG_C1_CLKS(0x00) | MCG_C1_FRDIV(0x05) | MCG_C1_IRCLKEN_MASK);                                   
  while((MCG_S & 0x0CU) != 0x0CU) {    /* Wait until output of the PLL is selected */
  }
  /*** End of PE initialization code after reset ***/

  /*** !!! Here you can place your own code after PE initialization using property "User code after PE initialization" on the build options tab. !!! ***/

}

/*
** ===================================================================
**     Method      :  Cpu_SetBASEPRI (component MK60DN512MC10)
**
**     Description :
**         This method sets the BASEPRI core register.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
/*lint -save  -e586 -e950 Disable MISRA rule (2.1,1.1) checking. */
#ifdef _lint
  #define Cpu_SetBASEPRI(Level)  /* empty */
#else
asm void Cpu_SetBASEPRI(register uint32_t Level) {
  MSR BASEPRI,R0;
  MOV PC,LR
}
#endif
/*lint -restore Enable MISRA rule (2.1,1.1) checking. */


/*
** ===================================================================
**     Method      :  PE_low_level_init (component MK60DN512MC10)
**
**     Description :
**         Initializes beans and provides common register initialization. 
**         The method is called automatically as a part of the 
**         application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void PE_low_level_init_26MHz(void)
{
  #ifdef PEX_RTOS_INIT
    PEX_RTOS_INIT();                   /* Initialization of the selected RTOS. Macro is defined by the RTOS component. */
  #endif
      /* Initialization of the SIM module */
  /* PORTA_PCR4: ISF=0,MUX=7 */
  PORTA_PCR4 = (uint32_t)((PORTA_PCR4 & (uint32_t)~(uint32_t)(
                PORT_PCR_ISF_MASK
               )) | (uint32_t)(
                PORT_PCR_MUX(0x07)
               ));                                  
        /* Initialization of the RCM module */
  /* RCM_RPFW: RSTFLTSEL=0 */
  RCM_RPFW &= (uint8_t)~(uint8_t)(RCM_RPFW_RSTFLTSEL(0x1F));                                   
  /* RCM_RPFC: RSTFLTSS=0,RSTFLTSRW=0 */
  RCM_RPFC &= (uint8_t)~(uint8_t)(
               RCM_RPFC_RSTFLTSS_MASK |
               RCM_RPFC_RSTFLTSRW(0x03)
              );                                   
  /* SIM_SCGC7: MPU=1 */
  SIM_SCGC7 |= SIM_SCGC7_MPU_MASK;                                   
        /* Initialization of the MPU module */
  /* MPU_CESR: SPERR=0,VLD=0 */
  MPU_CESR &= (uint32_t)~(uint32_t)((MPU_CESR_SPERR(0x1F) | MPU_CESR_VLD_MASK));                                   
      /* Initialization of the PMC module */
  /* PMC_LVDSC1: LVDACK=1,LVDIE=0,LVDRE=1,LVDV=0 */
  PMC_LVDSC1 = (uint8_t)((PMC_LVDSC1 & (uint8_t)~(uint8_t)(
                PMC_LVDSC1_LVDIE_MASK |
                PMC_LVDSC1_LVDV(0x03)
               )) | (uint8_t)(
                PMC_LVDSC1_LVDACK_MASK |
                PMC_LVDSC1_LVDRE_MASK
               ));                                  
  /* PMC_LVDSC2: LVWACK=1,LVWIE=0,LVWV=0 */
  PMC_LVDSC2 = (uint8_t)((PMC_LVDSC2 & (uint8_t)~(uint8_t)(
                PMC_LVDSC2_LVWIE_MASK |
                PMC_LVDSC2_LVWV(0x03)
               )) | (uint8_t)(
                PMC_LVDSC2_LVWACK_MASK
               ));                                  
  /* PMC_REGSC: BGEN=0,ACKISO=0,BGBE=0 */
  PMC_REGSC &= (uint8_t)~(uint8_t)(
                PMC_REGSC_BGEN_MASK |
                PMC_REGSC_ACKISO_MASK |
                PMC_REGSC_BGBE_MASK
               );                          
  
#if 0  // This is already done in BOOT2.
  
  /* SMC_PMPROT: ??=0,??=0,AVLP=1,??=0,ALLS=1,??=0,AVLLS=1,??=0 */
  SMC_PMPROT = SMC_PMPROT_AVLP_MASK |
               SMC_PMPROT_ALLS_MASK |
               SMC_PMPROT_AVLLS_MASK;  /* Setup Power mode protection register */
#endif
  
  /* Common initialization of the CPU registers */
                                 
  /* Common initialization of the CPU registers */
  /* NVICIP87: PRI87=0 */
  NVICIP87 = NVIC_IP_PRI87(0x00);                                   
  /* NVICIP88: PRI88=0 */
  NVICIP88 = NVIC_IP_PRI88(0x00);                                   
  /* NVICIP90: PRI90=0 */
  NVICIP90 = NVIC_IP_PRI90(0x00);                                   
  /* NVICIP91: PRI91=0 */
  NVICIP91 = NVIC_IP_PRI91(0x00);                                   
  /* NVICIP73: PRI73=0 */
  NVICIP73 = NVIC_IP_PRI73(0x00);                                   
  /* NVICIP20: PRI20=0 */
  NVICIP20 = NVIC_IP_PRI20(0x00);                                   

  /* ### Init_USB_OTG "USB_CORONA" init code ... */
  USB_CORONA_Init();
  /* ### RNG_LDD "RNG1" init code ... */
  /* Enable interrupts of the given priority level */
  Cpu_SetBASEPRI(0U);
}

/* END Cpu. */

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.0.12 [05.05]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
