/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.2.0 at Mon Feb 03 08:58:30 2014. */

#include "whistlemessage.pb.h"

const uint32_t WhistleMessage_progress_default = 0;


const pb_field_t WhistleMessage_fields[9] = {
    PB_FIELD(  1, ENUM    , OPTIONAL, STATIC, WhistleMessage, objectType, objectType, 0),
    PB_FIELD(  2, ENUM    , OPTIONAL, STATIC, WhistleMessage, transactionType, objectType, 0),
    PB_FIELD(  3, FIXED32 , OPTIONAL, STATIC, WhistleMessage, magicChecksum, transactionType, 0),
    PB_FIELD(  4, STRING  , OPTIONAL, CALLBACK, WhistleMessage, serialNumber, magicChecksum, 0),
    PB_FIELD(  5, BYTES   , OPTIONAL, CALLBACK, WhistleMessage, dataDump, serialNumber, 0),
    PB_FIELD(  6, MESSAGE , OPTIONAL, STATIC, WhistleMessage, remoteMgmtMsg, dataDump, &RemoteMgmtMsg_fields),
    PB_FIELD(  7, MESSAGE , OPTIONAL, STATIC, WhistleMessage, localMgmtMsg, remoteMgmtMsg, &LocalMgmtMsg_fields),
    PB_FIELD( 20, UINT32  , OPTIONAL, STATIC, WhistleMessage, progress, localMgmtMsg, &WhistleMessage_progress_default),
    PB_LAST_FIELD
};

const pb_field_t RemoteMgmtMsg_fields[10] = {
    PB_FIELD(  1, ENUM    , OPTIONAL, STATIC, RemoteMgmtMsg, messageType, messageType, 0),
    PB_FIELD(  2, MESSAGE , OPTIONAL, STATIC, RemoteMgmtMsg, checkInRequest, messageType, &RmCheckInRequest_fields),
    PB_FIELD(  3, MESSAGE , OPTIONAL, STATIC, RemoteMgmtMsg, checkInResponse, checkInRequest, &RmCheckInResponse_fields),
    PB_FIELD(  4, MESSAGE , OPTIONAL, STATIC, RemoteMgmtMsg, fwuManifestRequest, checkInResponse, &RmFwuManifestRequest_fields),
    PB_FIELD(  5, MESSAGE , OPTIONAL, STATIC, RemoteMgmtMsg, fwuManifestResponse, fwuManifestRequest, &RmFwuManifestResponse_fields),
    PB_FIELD(  6, MESSAGE , OPTIONAL, STATIC, RemoteMgmtMsg, fwuStatusPost, fwuManifestResponse, &RmFwuStatusPost_fields),
    PB_FIELD(  8, MESSAGE , OPTIONAL, STATIC, RemoteMgmtMsg, configRequest, fwuStatusPost, &RmConfigRequest_fields),
    PB_FIELD(  9, MESSAGE , OPTIONAL, STATIC, RemoteMgmtMsg, configResponse, configRequest, &RmConfigResponse_fields),
    PB_FIELD( 20, BYTES   , OPTIONAL, CALLBACK, RemoteMgmtMsg, payload, configResponse, 0),
    PB_LAST_FIELD
};

const pb_field_t RmCheckInRequest_fields[11] = {
    PB_FIELD(  1, ENUM    , OPTIONAL, STATIC, RmCheckInRequest, requestType, requestType, 0),
    PB_FIELD(  2, STRING  , OPTIONAL, CALLBACK, RmCheckInRequest, currentBoot1Version, requestType, 0),
    PB_FIELD(  3, STRING  , OPTIONAL, CALLBACK, RmCheckInRequest, currentBoot2Version, currentBoot1Version, 0),
    PB_FIELD(  4, STRING  , OPTIONAL, CALLBACK, RmCheckInRequest, currentAppVersion, currentBoot2Version, 0),
    PB_FIELD(  5, INT32   , OPTIONAL, STATIC, RmCheckInRequest, batteryLevel, currentAppVersion, 0),
    PB_FIELD(  6, UINT32  , OPTIONAL, STATIC, RmCheckInRequest, batteryCounts, batteryLevel, 0),
    PB_FIELD(  7, UINT32  , OPTIONAL, STATIC, RmCheckInRequest, temperatureCounts, batteryCounts, 0),
    PB_FIELD(  8, UINT32  , OPTIONAL, STATIC, RmCheckInRequest, wifiFWVersion, temperatureCounts, 0),
    PB_FIELD(  9, UINT32  , OPTIONAL, STATIC, RmCheckInRequest, currentMinutesActive, wifiFWVersion, 0),
    PB_FIELD( 10, ENUM    , OPTIONAL, STATIC, RmCheckInRequest, transportType, currentMinutesActive, 0),
    PB_LAST_FIELD
};

const pb_field_t RmCheckInResponse_fields[6] = {
    PB_FIELD(  1, ENUM    , OPTIONAL, STATIC, RmCheckInResponse, pendingAction, pendingAction, 0),
    PB_FIELD(  2, INT64   , OPTIONAL, STATIC, RmCheckInResponse, serverAbsoluteTime, pendingAction, 0),
    PB_FIELD(  3, STRING  , OPTIONAL, CALLBACK, RmCheckInResponse, bluetoothName, serverAbsoluteTime, 0),
    PB_FIELD(  4, INT32   , OPTIONAL, STATIC, RmCheckInResponse, activityGoal, bluetoothName, 0),
    PB_FIELD(  5, SINT32  , OPTIONAL, STATIC, RmCheckInResponse, utcOffsetSeconds, activityGoal, 0),
    PB_LAST_FIELD
};

const pb_field_t RmFwuManifestRequest_fields[4] = {
    PB_FIELD(  1, STRING  , OPTIONAL, CALLBACK, RmFwuManifestRequest, currentBoot1Version, currentBoot1Version, 0),
    PB_FIELD(  2, STRING  , OPTIONAL, CALLBACK, RmFwuManifestRequest, currentBoot2Version, currentBoot1Version, 0),
    PB_FIELD(  3, STRING  , OPTIONAL, CALLBACK, RmFwuManifestRequest, currentAppVersion, currentBoot2Version, 0),
    PB_LAST_FIELD
};

const pb_field_t RmFwuManifestResponse_fields[3] = {
    PB_FIELD(  1, STRING  , OPTIONAL, CALLBACK, RmFwuManifestResponse, firmwareUpdateVersion, firmwareUpdateVersion, 0),
    PB_FIELD(  2, STRING  , OPTIONAL, CALLBACK, RmFwuManifestResponse, packageUrl, firmwareUpdateVersion, 0),
    PB_LAST_FIELD
};

const pb_field_t RmFwuStatusPost_fields[6] = {
    PB_FIELD(  1, STRING  , OPTIONAL, CALLBACK, RmFwuStatusPost, attemptedFirmwareUpdateVersion, attemptedFirmwareUpdateVersion, 0),
    PB_FIELD(  2, ENUM    , OPTIONAL, STATIC, RmFwuStatusPost, status, attemptedFirmwareUpdateVersion, 0),
    PB_FIELD(  3, STRING  , OPTIONAL, CALLBACK, RmFwuStatusPost, attemptedBoot1Version, status, 0),
    PB_FIELD(  4, STRING  , OPTIONAL, CALLBACK, RmFwuStatusPost, attemptedBoot2Version, attemptedBoot1Version, 0),
    PB_FIELD(  5, STRING  , OPTIONAL, CALLBACK, RmFwuStatusPost, attemptedAppVersion, attemptedBoot2Version, 0),
    PB_LAST_FIELD
};

const pb_field_t RmConfigRequest_fields[3] = {
    PB_FIELD(  1, INT64   , OPTIONAL, STATIC, RmConfigRequest, currentStreamConfigVersion, currentStreamConfigVersion, 0),
    PB_FIELD(  2, INT64   , OPTIONAL, STATIC, RmConfigRequest, currentUniqueConfigVersion, currentStreamConfigVersion, 0),
    PB_LAST_FIELD
};

const pb_field_t RmConfigItem_fields[3] = {
    PB_FIELD(  1, STRING  , OPTIONAL, CALLBACK, RmConfigItem, type, type, 0),
    PB_FIELD(  2, STRING  , OPTIONAL, CALLBACK, RmConfigItem, value, type, 0),
    PB_LAST_FIELD
};

const pb_field_t RmConfigResponse_fields[4] = {
    PB_FIELD(  1, INT64   , OPTIONAL, STATIC, RmConfigResponse, streamConfigVersion, streamConfigVersion, 0),
    PB_FIELD(  2, INT64   , OPTIONAL, STATIC, RmConfigResponse, uniqueConfigVersion, streamConfigVersion, 0),
    PB_FIELD(  3, MESSAGE , REPEATED, CALLBACK, RmConfigResponse, configItem, uniqueConfigVersion, &RmConfigItem_fields),
    PB_LAST_FIELD
};

const pb_field_t LocalMgmtMsg_fields[3] = {
    PB_FIELD(  1, ENUM    , OPTIONAL, STATIC, LocalMgmtMsg, messageType, messageType, 0),
    PB_FIELD( 21, BYTES   , OPTIONAL, CALLBACK, LocalMgmtMsg, payload, messageType, 0),
    PB_LAST_FIELD
};

const pb_field_t LmMobileStatRequest_fields[6] = {
    PB_FIELD(  1, ENUM    , OPTIONAL, STATIC, LmMobileStatRequest, initType, initType, 0),
    PB_FIELD(  2, INT64   , OPTIONAL, STATIC, LmMobileStatRequest, mobileBTMAC, initType, 0),
    PB_FIELD(  3, INT32   , OPTIONAL, STATIC, LmMobileStatRequest, batteryLevel, mobileBTMAC, 0),
    PB_FIELD(  4, STRING  , OPTIONAL, CALLBACK, LmMobileStatRequest, wifiMac, batteryLevel, 0),
    PB_FIELD(  5, STRING  , OPTIONAL, CALLBACK, LmMobileStatRequest, wifiVer, wifiMac, 0),
    PB_LAST_FIELD
};

const pb_field_t LmMobileStat_fields[3] = {
    PB_FIELD(  1, ENUM    , OPTIONAL, STATIC, LmMobileStat, status, status, 0),
    PB_FIELD(  2, INT64   , OPTIONAL, STATIC, LmMobileStat, serverAbsoluteTime, status, 0),
    PB_LAST_FIELD
};

const pb_field_t LmWiFiNetwork_fields[7] = {
    PB_FIELD(  1, STRING  , OPTIONAL, CALLBACK, LmWiFiNetwork, ssid, ssid, 0),
    PB_FIELD(  2, ENUM    , OPTIONAL, STATIC, LmWiFiNetwork, type, ssid, 0),
    PB_FIELD(  3, ENUM    , OPTIONAL, STATIC, LmWiFiNetwork, uCipher, type, 0),
    PB_FIELD(  4, ENUM    , OPTIONAL, STATIC, LmWiFiNetwork, mCipher, uCipher, 0),
    PB_FIELD(  5, BOOL    , OPTIONAL, STATIC, LmWiFiNetwork, isHidden, mCipher, 0),
    PB_FIELD(  6, STRING  , OPTIONAL, CALLBACK, LmWiFiNetwork, password, isHidden, 0),
    PB_LAST_FIELD
};

const pb_field_t LmWiFiScanResponse_fields[2] = {
    PB_FIELD(  1, MESSAGE , REPEATED, CALLBACK, LmWiFiScanResponse, network, network, &LmWiFiNetwork_fields),
    PB_LAST_FIELD
};

const pb_field_t LmWiFiTestRequest_fields[2] = {
    PB_FIELD(  1, MESSAGE , OPTIONAL, STATIC, LmWiFiTestRequest, network, network, &LmWiFiNetwork_fields),
    PB_LAST_FIELD
};

const pb_field_t LmWiFiTestResponse_fields[3] = {
    PB_FIELD(  1, ENUM    , OPTIONAL, STATIC, LmWiFiTestResponse, status, status, 0),
    PB_FIELD(  2, MESSAGE , OPTIONAL, STATIC, LmWiFiTestResponse, network, status, &LmWiFiNetwork_fields),
    PB_LAST_FIELD
};

const pb_field_t LmWiFiAddRequest_fields[2] = {
    PB_FIELD(  1, MESSAGE , OPTIONAL, STATIC, LmWiFiAddRequest, network, network, &LmWiFiNetwork_fields),
    PB_LAST_FIELD
};

const pb_field_t LmWiFiAddResponse_fields[3] = {
    PB_FIELD(  1, ENUM    , OPTIONAL, STATIC, LmWiFiAddResponse, status, status, 0),
    PB_FIELD(  2, MESSAGE , OPTIONAL, STATIC, LmWiFiAddResponse, network, status, &LmWiFiNetwork_fields),
    PB_LAST_FIELD
};

const pb_field_t LmWiFiRemRequest_fields[2] = {
    PB_FIELD(  1, STRING  , OPTIONAL, CALLBACK, LmWiFiRemRequest, ssid, ssid, 0),
    PB_LAST_FIELD
};

const pb_field_t LmWiFiRemResponse_fields[3] = {
    PB_FIELD(  1, ENUM    , OPTIONAL, STATIC, LmWiFiRemResponse, status, status, 0),
    PB_FIELD(  2, STRING  , OPTIONAL, CALLBACK, LmWiFiRemResponse, ssid, status, 0),
    PB_LAST_FIELD
};

const pb_field_t LmDevStat_fields[2] = {
    PB_FIELD(  1, ENUM    , OPTIONAL, STATIC, LmDevStat, status, status, 0),
    PB_LAST_FIELD
};

const pb_field_t LmWiFiListResponse_fields[2] = {
    PB_FIELD(  1, MESSAGE , REPEATED, CALLBACK, LmWiFiListResponse, network, network, &LmWiFiNetwork_fields),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
STATIC_ASSERT((pb_membersize(WhistleMessage, remoteMgmtMsg) < 256 && pb_membersize(WhistleMessage, localMgmtMsg) < 256 && pb_membersize(RemoteMgmtMsg, checkInRequest) < 256 && pb_membersize(RemoteMgmtMsg, checkInResponse) < 256 && pb_membersize(RemoteMgmtMsg, fwuManifestRequest) < 256 && pb_membersize(RemoteMgmtMsg, fwuManifestResponse) < 256 && pb_membersize(RemoteMgmtMsg, fwuStatusPost) < 256 && pb_membersize(RemoteMgmtMsg, configRequest) < 256 && pb_membersize(RemoteMgmtMsg, configResponse) < 256 && pb_membersize(RmConfigResponse, configItem) < 256 && pb_membersize(LmWiFiScanResponse, network) < 256 && pb_membersize(LmWiFiTestRequest, network) < 256 && pb_membersize(LmWiFiTestResponse, network) < 256 && pb_membersize(LmWiFiAddRequest, network) < 256 && pb_membersize(LmWiFiAddResponse, network) < 256 && pb_membersize(LmWiFiListResponse, network) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_WhistleMessage_RemoteMgmtMsg_RmCheckInRequest_RmCheckInResponse_RmFwuManifestRequest_RmFwuManifestResponse_RmFwuStatusPost_RmConfigRequest_RmConfigItem_RmConfigResponse_LocalMgmtMsg_LmMobileStatRequest_LmMobileStat_LmWiFiNetwork_LmWiFiScanResponse_LmWiFiTestRequest_LmWiFiTestResponse_LmWiFiAddRequest_LmWiFiAddResponse_LmWiFiRemRequest_LmWiFiRemResponse_LmDevStat_LmWiFiListResponse)
#endif

#if !defined(PB_FIELD_32BIT)
STATIC_ASSERT((pb_membersize(WhistleMessage, remoteMgmtMsg) < 65536 && pb_membersize(WhistleMessage, localMgmtMsg) < 65536 && pb_membersize(RemoteMgmtMsg, checkInRequest) < 65536 && pb_membersize(RemoteMgmtMsg, checkInResponse) < 65536 && pb_membersize(RemoteMgmtMsg, fwuManifestRequest) < 65536 && pb_membersize(RemoteMgmtMsg, fwuManifestResponse) < 65536 && pb_membersize(RemoteMgmtMsg, fwuStatusPost) < 65536 && pb_membersize(RemoteMgmtMsg, configRequest) < 65536 && pb_membersize(RemoteMgmtMsg, configResponse) < 65536 && pb_membersize(RmConfigResponse, configItem) < 65536 && pb_membersize(LmWiFiScanResponse, network) < 65536 && pb_membersize(LmWiFiTestRequest, network) < 65536 && pb_membersize(LmWiFiTestResponse, network) < 65536 && pb_membersize(LmWiFiAddRequest, network) < 65536 && pb_membersize(LmWiFiAddResponse, network) < 65536 && pb_membersize(LmWiFiListResponse, network) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_WhistleMessage_RemoteMgmtMsg_RmCheckInRequest_RmCheckInResponse_RmFwuManifestRequest_RmFwuManifestResponse_RmFwuStatusPost_RmConfigRequest_RmConfigItem_RmConfigResponse_LocalMgmtMsg_LmMobileStatRequest_LmMobileStat_LmWiFiNetwork_LmWiFiScanResponse_LmWiFiTestRequest_LmWiFiTestResponse_LmWiFiAddRequest_LmWiFiAddResponse_LmWiFiRemRequest_LmWiFiRemResponse_LmDevStat_LmWiFiListResponse)
#endif

